### ISSUE TITLE
Should we update UITransition 

### ISSUE THREAD

**Issue by takaaptech** [mob-sakai/UITransition#14]
I think a plugin that supports window manager will work best with UITransition.
For example, in a game: we will support creating windows for the game menu (panel) and setting menu (overlay). And then when we transition from game menu to setting menu, the UI component like button and game title label will transition base on UITransition.
I mean we should use this awesome plugin with something like UISystem that support stacks and manage screens (popup, window, panels ..) transition.
Thank so much!

**Comment by mob-sakai** [comment]
Hi, @takaaptech !
Thank you for using UITransition.

Yes, exactly right!
UITransition adapts to window management system.

In fact, we are developing UITransition as a subsystem of [UISystem](https://github.com/mob-sakai/UISystem/tree/develop).
Of course, you can also use UITransition independently :)

What is the window management system you use?
We might be able to support that window management system.

**Comment by takaaptech** [comment]
Hi @mob-sakai!
After viewing UISystem in "develop branch", I think that is enough for us to continually improve feature!
I try some other plugins like: 
https://assetstore.unity.com/packages/tools/utilities/easy-front-end-56866 (free)
https://assetstore.unity.com/packages/tools/gui/zui-menus-manager-96251 (9.99$)

And recently I am using UI System from this:
https://github.com/GaoKaiHaHa/MyUnityFrameWork
 - Very clear and have many Event like OnInit, OnShow, OnRefresh likes us
 - Easy for handling data between screen via GlobalEvent
 - And they have some concept of State that can separate each screen for testing.
 - Difference layer for many kinds of UI like Normal, TopBar, Overlay...

And I think we have a good start with UISystem! So maybe you can use it for reference and improve UISystem!

**Comment by mob-sakai** [comment]
Thank you for information 👍 

Hmm, they are very nice plugins!
We will develop and improve our UISystem with reference to them!

**Comment by takaaptech** [comment]
Yes yes! And please release to master a version soon!
It will be great if you include an example, I will try to use and comment as much as I can!!!
Thank so much @mob-sakai!

**Comment by mob-sakai** [comment]
:+1:
